environment:
  matrix:
    - PYTHON: "C:\\Python26"
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python312"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      INSTALL_SETUPTOOLS: "1"
    - PYTHON: "C:\\Python313"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      INSTALL_SETUPTOOLS: "1"
    - PYTHON: "C:\\Python26-x64"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python312-x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      INSTALL_SETUPTOOLS: "1"
    - PYTHON: "C:\\Python313-x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      INSTALL_SETUPTOOLS: "1"

build: off

test_script:
  - "build.cmd %PYTHON%\\python.exe setup.py test"

after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_egg"

artifacts:
  - path: dist\*
